apiVersion: v1
kind: Service
metadata:
  name: consumesafe-backend
  namespace: consumesafe
spec:
  selector:
    app: consumesafe-backend
  ports:
    - name: http
      port: 5050
      targetPort: 5050
